name: example
description: Demonstrates how to use the smartup_uikit plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  smartup_uikit:
    path: ../
  cupertino_icons: ^1.0.2
  built_collection: ^5.1.1
  built_value: ^8.4.1
  flutter_gen: ^5.0.1
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  built_value_generator: ^8.4.1
  flutter_gen_runner: ^5.0.1
  icons_launcher: ^2.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
