import 'package:example/constants/example_colors.dart';
import 'package:example/constants/example_typography.dart';
import 'package:flutter/material.dart';
import 'package:smartup_uikit/smartup_uikit.dart';

UIKitThemeData kitThemeData = UIKitThemeData(
  buttonThemeData: UIKitButtonThemeData(
    primaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      hoverBackgroundColor: ExampleColors.primary800,
      focusedBackgroundColor: ExampleColors.primary800,
      activeBackgroundColor: ExampleColors.primary800,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondaryW,
      hoverContentColor: ExampleColors.secondaryW,
      focusedContentColor: ExampleColors.secondaryW,
      activeContentColor: ExampleColors.secondaryW,
      disabledContentColor: ExampleColors.secondary300,
    ),
    secondaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary50,
      hoverBackgroundColor: ExampleColors.primary100,
      focusedBackgroundColor: ExampleColors.primary100,
      activeBackgroundColor: ExampleColors.primary100,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary700,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700,
    ),
    secondaryWhiteColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary700,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700,
    ),
    tertiaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary50,
      hoverBackgroundColor: ExampleColors.secondary50,
      focusedBackgroundColor: ExampleColors.secondary200,
      activeBackgroundColor: ExampleColors.secondary50,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary700,
      hoverContentColor: ExampleColors.secondary800,
      focusedContentColor: ExampleColors.secondary800,
      activeContentColor: ExampleColors.secondaryK,
      disabledContentColor: ExampleColors.secondary700,
    ),
    outlineColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.primary50,
      activeBackgroundColor: ExampleColors.primary50,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.primary700,
      hoverBorderColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary800,
      disabledBorderColor: ExampleColors.primary700.withOpacity(0.3),
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary800,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    ghostColors: UIKitColorScheme(
      defaultBackgroundColor: Colors.transparent,
      hoverBackgroundColor: Colors.transparent,
      focusedBackgroundColor: Colors.transparent,
      activeBackgroundColor: Colors.transparent,
      disabledBackgroundColor: Colors.transparent,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: ExampleColors.secondary300,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary700,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    solidIconColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      hoverBackgroundColor: ExampleColors.primary800,
      focusedBackgroundColor: ExampleColors.primary800,
      activeBackgroundColor: ExampleColors.primary800,
      disabledBackgroundColor: ExampleColors.primary700.withOpacity(0.3),
      defaultBorderColor: ExampleColors.primary800,
      hoverBorderColor: ExampleColors.primary900,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary900,
      disabledBorderColor: ExampleColors.primary800.withOpacity(0.3),
      defaultContentColor: ExampleColors.secondaryW,
      hoverContentColor: ExampleColors.secondaryW,
      focusedContentColor: ExampleColors.secondaryW,
      activeContentColor: ExampleColors.secondaryW,
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.3),
    ),
    ghostIconColors: UIKitColorScheme(
      defaultBackgroundColor: Colors.transparent,
      hoverBackgroundColor: ExampleColors.primary50,
      focusedBackgroundColor: ExampleColors.primary100,
      activeBackgroundColor: ExampleColors.primary100,
      disabledBackgroundColor: ExampleColors.primary30.withOpacity(0.3),
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    solidIconShadows: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      hoverShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 4,
          spreadRadius: 0,
        ),
      ],
      activeShadow: [],
      disabledShadow: [],
    ),
    smallSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 8),
      leadingSize: 16,
      trailingSize: 16,
      iconSize: 16,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsSmall,
    ),
    mediumSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      leadingSize: 20,
      trailingSize: 20,
      iconSize: 20,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsMedium,
    ),
    largeSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 9, horizontal: 24),
      leadingSize: 20,
      trailingSize: 20,
      iconSize: 20,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsLarge,
    ),
    smallIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(4),
      trailingSize: 16,
      borderRadius: 8,
    ),
    mediumIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(6),
      trailingSize: 20,
      borderRadius: 8,
    ),
    largeIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(10),
      trailingSize: 20,
      borderRadius: 8,
    ),
  ),
  menuItemThemeData: UIKitMenuItemThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary500,
      hoverBackgroundColor: ExampleColors.primary500,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.primary700,
      activeBorderColor: Colors.transparent,
      activeContentColor: ExampleColors.secondaryW,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.all(8),
      spacing: 8,
      leadingSize: 24,
      labelStyle: ExampleTypography.body2SemiBold,
    ),
  ),
  radioButtonThemeData: UIKitRadioButtonThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.primary700,
      hoverBorderColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary800,
      disabledBorderColor: ExampleColors.secondary300,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.all(3),
      width: 20,
      height: 20,
      borderSize: 1.6,
      spacing: 16,
      secondarySpacing: 8,
    ),
    shadowScheme: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 2,
          spreadRadius: 0,
        ),
      ],
    ),
  ),
  radioGroupThemeData: UIKitRadioGroupThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary900,
      defaultContentColor: ExampleColors.secondary700,
      defaultSecondaryContentColor: ExampleColors.secondary400,
      errorBackgroundColor: ExampleColors.primary900,
      errorContentColor: ExampleColors.secondary800,
      errorSecondaryContentColor: ExampleColors.primary900,
      disabledBackgroundColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledSecondaryContentColor:
          ExampleColors.secondary300.withOpacity(0.7),
    ),
    smallSize: UIKitSizeScheme(
      width: 4,
      height: 6,
      spacing: 4,
      secondarySpacing: 16,
      iconSize: 16,
      labelStyle: ExampleTypography.bodySSemiBold,
      inputStyle: ExampleTypography.body3Regular,
      assistiveStyle: ExampleTypography.bodySRegular,
    ),
    mediumSize: UIKitSizeScheme(
      width: 4,
      height: 12,
      spacing: 6,
      secondarySpacing: 24,
      iconSize: 16,
      labelStyle: ExampleTypography.body3SemiBold,
      inputStyle: ExampleTypography.body2Regular,
      assistiveStyle: ExampleTypography.body3Regular,
    ),
    largeSize: UIKitSizeScheme(
      width: 4,
      height: 6,
      spacing: 8,
      secondarySpacing: 32,
      iconSize: 16,
      labelStyle: ExampleTypography.body2SemiBold,
      inputStyle: ExampleTypography.body1Regular,
      assistiveStyle: ExampleTypography.body2Regular,
    ),
  ),
  toggleSwitchThemeData: UIKitToggleSwitchThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary100,
      defaultBorderColor: ExampleColors.primary800,
      defaultContentColor: ExampleColors.primary700,
      defaultSecondaryContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondary100,
      hoverBorderColor: ExampleColors.primary900,
      hoverContentColor: ExampleColors.primary800,
      hoverSecondaryContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondary100,
      activeBorderColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary800,
      activeSecondaryContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondary100,
      focusedBorderColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary700,
      focusedSecondaryContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary50.withOpacity(0.7),
      disabledBorderColor: Colors.transparent.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledSecondaryContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    shadowScheme: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      hoverShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      activeShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
    ),
    largeSize: UIKitSizeScheme(
      width: 48,
      height: 24,
      borderSize: 1,
      spacing: 20,
      iconSize: 16,
    ),
    smallSize: UIKitSizeScheme(
      width: 40,
      height: 20,
      borderSize: 1,
      spacing: 16.67,
      iconSize: 13,
    ),
  ),
  checkboxThemeData: UIKitCheckboxThemeData(
    checkedColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      defaultBorderColor: ExampleColors.primary700,
      defaultContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.primary800,
      hoverBorderColor: ExampleColors.primary800,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.primary800,
      activeBorderColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    uncheckedColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.secondary800,
      defaultContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      hoverBorderColor: ExampleColors.secondary800,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      activeBorderColor: ExampleColors.secondary800,
      activeContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      focusedBorderColor: ExampleColors.secondary800,
      focusedContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    shadowScheme: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 2,
          spreadRadius: 0,
        ),
      ],
    ),
    sizeScheme: UIKitSizeScheme(
      width: 20,
      height: 20,
      iconSize: 16,
      padding: const EdgeInsets.all(2),
      borderSize: 1,
      borderRadius: 6,
    ),
  ),
);

UIKitTextInputThemeData kitTextInputThemeData = UIKitTextInputThemeData(
  filledInputcolorScheme: UIKitColorScheme(
    defaultBackgroundColor: ExampleColors.secondary50,
    hoverBackgroundColor: ExampleColors.secondary100,
    focusedBackgroundColor: ExampleColors.secondaryW,
    activeBackgroundColor: ExampleColors.secondary50,
    disabledBackgroundColor: ExampleColors.secondary30,
    defaultBorderColor: ExampleColors.primary800,
    hoverBorderColor: ExampleColors.primary900,
    focusedBorderColor: ExampleColors.primary900,
    activeBorderColor: ExampleColors.primary900,
    disabledBorderColor: ExampleColors.primary800.withOpacity(0.3),
    defaultContentColor: ExampleColors.secondaryW,
    hoverContentColor: ExampleColors.secondaryW,
    focusedContentColor: ExampleColors.secondaryW,
    activeContentColor: ExampleColors.secondaryW,
    disabledContentColor: ExampleColors.secondaryW.withOpacity(0.3),
  ),
  lineInputcolorScheme: UIKitColorScheme(),
  filledSearchcolorScheme: UIKitColorScheme(),
  lineSearchcolorScheme: UIKitColorScheme(),
  inputSizeScheme: UIKitSizeScheme(),
  searchSizeScheme: UIKitSizeScheme(),
  shadowScheme: UIKitShadowScheme(),
);
