import 'package:example/constants/example_colors.dart';
import 'package:example/constants/example_typography.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:smartup_uikit/smartup_uikit.dart';

UIKitThemeData kitThemeData = UIKitThemeData(
  colors: const UIKitColors(
    primary30: Color(0xFFFFF7F7),
    primary50: Color(0xFFFFF0F1),
    primary100: Color(0xFFFFE1E3),
    primary200: Color(0xFFFDB0B5),
    primary300: Color(0xFFFA959C),
    primary400: Color(0xFFF5757D),
    primary500: Color(0xFFF07087),
    primary600: Color(0xFFE9405E),
    primary700: Color(0xFFD81A3C),
    primary800: Color(0xFFC00E2E),
    primary900: Color(0xFFA0031F),
    primaryK: Color(0xFF640012),
    secondaryW: Color(0xFFFFFFFF),
    secondary30: Color(0xFFF5F5FF),
    secondary50: Color(0xFFF1F1FB),
    secondary100: Color(0xFFE8E8F3),
    secondary200: Color(0xFFD5D5E6),
    secondary300: Color(0xFFB1B1BF),
    secondary400: Color(0xFF83838D),
    secondary500: Color(0xFF6B6B75),
    secondary600: Color(0xFF575760),
    secondary700: Color(0xFF3F3F47),
    secondary800: Color(0xFF2F2F37),
    secondary900: Color(0xFF212126),
    secondaryK: Color(0xFF121214),
    success50: Color(0xFFF0FCF9),
    success100: Color(0xFFC5EFE6),
    success300: Color(0xFF66EBCE),
    success500: Color(0xFF4EDBB9),
    success700: Color(0xFF0ECB9D),
    success800: Color(0xFF0CB089),
    warning50: Color(0xFFFBF0EA),
    warning100: Color(0xFFFEE8DB),
    warning300: Color(0xFFFFCDB0),
    warning500: Color(0xFFF89F6D),
    warning700: Color(0xFFE7702D),
    warning800: Color(0xFFCF530D),
  ),
  typography: UIKitTypography(
    headings1Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 38,
      height: 1.48,
      letterSpacing: -0.02,
    ),
    headings1Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 38,
      height: 1.48,
      letterSpacing: -0.02,
    ),
    headings2Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 30,
      height: 1.48,
      letterSpacing: -0.02,
    ),
    headings2Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 30,
      height: 1.48,
      letterSpacing: -0.02,
    ),
    headings3Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 24,
      height: 1.5,
      letterSpacing: -0.02,
    ),
    headings3Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 24,
      height: 1.5,
      letterSpacing: -0.02,
    ),
    headings4Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 20,
      height: 1.5,
      letterSpacing: -0.02,
    ),
    headings4Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 20,
      height: 1.5,
      letterSpacing: -0.02,
    ),
    headings5Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 18,
      height: 1.36,
      letterSpacing: -0.02,
    ),
    headings5Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 18,
      height: 1.36,
      letterSpacing: -0.02,
    ),
    body1Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 16,
      height: 1.36,
      letterSpacing: -0.02,
    ),
    body1SemiBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 16,
      height: 1.36,
      letterSpacing: -0.02,
    ),
    body1Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 16,
      height: 1.36,
      letterSpacing: -0.02,
    ),
    body2Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 14,
      height: 1.4,
      letterSpacing: -0.02,
    ),
    body2SemiBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 14,
      height: 1.4,
      letterSpacing: -0.02,
    ),
    body2Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 14,
      height: 1.4,
      letterSpacing: -0.02,
    ),
    body3Bold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 12,
      height: 1.36,
      letterSpacing: -0.01,
    ),
    body3SemiBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 12,
      height: 1.36,
      letterSpacing: -0.01,
    ),
    body3Regular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 12,
      height: 1.36,
      letterSpacing: -0.01,
    ),
    bodySBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 11,
      height: 1.46,
      letterSpacing: 0,
    ),
    bodySSemiBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 11,
      height: 1.46,
      letterSpacing: 0,
    ),
    bodySRegular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 11,
      height: 1.46,
      letterSpacing: 0,
    ),
    bodyXSXBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w800,
      fontSize: 10,
      height: 1.36,
      letterSpacing: 0.08,
    ),
    bodyXSBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w700,
      fontSize: 10,
      height: 1.36,
      letterSpacing: 0.003,
    ),
    bodyXSSemiBold: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 10,
      height: 1.36,
      letterSpacing: 0.003,
    ),
    bodyXSRegular: GoogleFonts.openSans(
      fontWeight: FontWeight.w400,
      fontSize: 10,
      height: 1.36,
      letterSpacing: 0.003,
    ),
    buttonsLarge: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 17,
      height: 1.5,
      letterSpacing: -0.02,
    ),
    buttonsMedium: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 15,
      height: 1.46,
      letterSpacing: -0.02,
    ),
    buttonsSmall: GoogleFonts.openSans(
      fontWeight: FontWeight.w600,
      fontSize: 13,
      height: 1.36,
      letterSpacing: -0.02,
    ),
  ),
  toggleSwitchListTileThemeData: UIKitToggleSwitchListTileThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.secondaryW,
      defaultContentColor: ExampleColors.primary700,
      defaultSecondaryContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondary100,
      hoverBorderColor: ExampleColors.secondaryW,
      hoverContentColor: ExampleColors.primary800,
      hoverSecondaryContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondary100,
      activeBorderColor: ExampleColors.secondaryW,
      activeContentColor: ExampleColors.primary800,
      activeSecondaryContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondary100,
      focusedBorderColor: ExampleColors.secondaryW,
      focusedContentColor: ExampleColors.primary800,
      focusedSecondaryContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary50.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondaryW,
      disabledContentColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledSecondaryContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    smallSize: UIKitSizeScheme(
      //distance between the label and the toggle
      spacing: 8,
      //with of the whole widget
      width: 90,
      //height of the whole widget (might include padding?)
      height: 12,
      //height of the toggle
      iconSize: 12,
    ),
    mediumSize: UIKitSizeScheme(
      //distance between the label and the checkbox
      spacing: 15,
      //with of the whole widget
      width: 180,
      //height of the whole widget (might include padding?)
      height: 24,
      //height of the checkmark
      iconSize: 24,
    ),
    largeSize: UIKitSizeScheme(
      //distance between the label and the checkbox
      spacing: 30,
      //with of the whole widget
      width: 300,
      //height of the whole widget (might include padding?)
      height: 24,
      //height of the toggle
      iconSize: 48,
    ),
  ),
  buttonThemeData: UIKitButtonThemeData(
    primaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      hoverBackgroundColor: ExampleColors.primary800,
      focusedBackgroundColor: ExampleColors.primary800,
      activeBackgroundColor: ExampleColors.primary800,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondaryW,
      hoverContentColor: ExampleColors.secondaryW,
      focusedContentColor: ExampleColors.secondaryW,
      activeContentColor: ExampleColors.secondaryW,
      disabledContentColor: ExampleColors.secondary300,
    ),
    secondaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary50,
      hoverBackgroundColor: ExampleColors.primary100,
      focusedBackgroundColor: ExampleColors.primary100,
      activeBackgroundColor: ExampleColors.primary100,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary700,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700,
    ),
    secondaryWhiteColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary700,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700,
    ),
    tertiaryColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary50,
      hoverBackgroundColor: ExampleColors.secondary50,
      focusedBackgroundColor: ExampleColors.secondary200,
      activeBackgroundColor: ExampleColors.secondary50,
      disabledBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary700,
      hoverContentColor: ExampleColors.secondary800,
      focusedContentColor: ExampleColors.secondary800,
      activeContentColor: ExampleColors.secondaryK,
      disabledContentColor: ExampleColors.secondary700,
    ),
    outlineColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.primary50,
      activeBackgroundColor: ExampleColors.primary50,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.primary700,
      hoverBorderColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary800,
      disabledBorderColor: ExampleColors.primary700.withOpacity(0.3),
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary800,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    ghostColors: UIKitColorScheme(
      defaultBackgroundColor: Colors.transparent,
      hoverBackgroundColor: Colors.transparent,
      focusedBackgroundColor: Colors.transparent,
      activeBackgroundColor: Colors.transparent,
      disabledBackgroundColor: Colors.transparent,
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: ExampleColors.secondary300,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary700,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    solidIconColors: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      hoverBackgroundColor: ExampleColors.primary800,
      focusedBackgroundColor: ExampleColors.primary800,
      activeBackgroundColor: ExampleColors.primary800,
      disabledBackgroundColor: ExampleColors.primary700.withOpacity(0.3),
      defaultBorderColor: ExampleColors.primary800,
      hoverBorderColor: ExampleColors.primary900,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary900,
      disabledBorderColor: ExampleColors.primary800.withOpacity(0.3),
      defaultContentColor: ExampleColors.secondaryW,
      hoverContentColor: ExampleColors.secondaryW,
      focusedContentColor: ExampleColors.secondaryW,
      activeContentColor: ExampleColors.secondaryW,
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.3),
    ),
    ghostIconColors: UIKitColorScheme(
      defaultBackgroundColor: Colors.transparent,
      hoverBackgroundColor: ExampleColors.primary50,
      focusedBackgroundColor: ExampleColors.primary100,
      activeBackgroundColor: ExampleColors.primary100,
      disabledBackgroundColor: ExampleColors.primary30.withOpacity(0.3),
      defaultBorderColor: Colors.transparent,
      hoverBorderColor: Colors.transparent,
      focusedBorderColor: Colors.transparent,
      activeBorderColor: Colors.transparent,
      disabledBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.primary700,
      hoverContentColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.primary900,
      disabledContentColor: ExampleColors.primary700.withOpacity(0.3),
    ),
    solidIconShadows: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      hoverShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 4,
          spreadRadius: 0,
        ),
      ],
      activeShadow: [],
      disabledShadow: [],
    ),
    smallSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 8),
      leadingSize: 16,
      trailingSize: 16,
      iconSize: 16,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsSmall,
    ),
    mediumSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      leadingSize: 20,
      trailingSize: 20,
      iconSize: 20,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsMedium,
    ),
    largeSize: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 9, horizontal: 24),
      leadingSize: 20,
      trailingSize: 20,
      iconSize: 20,
      spacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.buttonsLarge,
    ),
    smallIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(4),
      trailingSize: 16,
      borderRadius: 8,
    ),
    mediumIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(6),
      trailingSize: 20,
      borderRadius: 8,
    ),
    largeIconSize: UIKitSizeScheme(
      padding: const EdgeInsets.all(10),
      trailingSize: 20,
      borderRadius: 8,
    ),
  ),
  checkboxThemeData: UIKitCheckboxThemeData(
    checkedColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.primary700,
      defaultBorderColor: ExampleColors.primary700,
      defaultContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.primary800,
      hoverBorderColor: ExampleColors.primary800,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.primary800,
      activeBorderColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    uncheckedColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.secondary800,
      defaultContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      hoverBorderColor: ExampleColors.secondary800,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      activeBorderColor: ExampleColors.secondary800,
      activeContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      focusedBorderColor: ExampleColors.secondary800,
      focusedContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    shadowScheme: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 2,
          spreadRadius: 0,
        ),
      ],
    ),
    sizeScheme: UIKitSizeScheme(
      width: 20,
      height: 20,
      iconSize: 16,
      padding: const EdgeInsets.all(2),
      borderSize: 1,
      borderRadius: 6,
    ),
  ),
  menuItemThemeData: UIKitMenuItemThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary500,
      defaultSecondaryContentColor: ExampleColors.secondary300,
      hoverBackgroundColor: ExampleColors.primary500,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondaryW,
      hoverSecondaryContentColor: ExampleColors.primary700,
      activeBackgroundColor: ExampleColors.primary700,
      activeBorderColor: Colors.transparent,
      activeContentColor: ExampleColors.secondaryW,
      activeSecondaryContentColor: ExampleColors.primary700,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 8),
      spacing: 8,
      leadingSize: 20,
      trailingSize: 20,
      labelStyle: ExampleTypography.body2Regular,
    ),
    shadowScheme: UIKitShadowScheme.defaultScheme(),
  ),
  radioButtonThemeData: UIKitRadioButtonThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.primary700,
      hoverBorderColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary900,
      activeBorderColor: ExampleColors.primary800,
      disabledBorderColor: ExampleColors.secondary300,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.all(3),
      width: 20,
      height: 20,
      borderSize: 1.6,
      spacing: 16,
      secondarySpacing: 8,
    ),
    shadowScheme: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 2,
          spreadRadius: 0,
        ),
      ],
    ),
  ),
  radioGroupThemeData: UIKitRadioGroupThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary900,
      defaultContentColor: ExampleColors.secondary700,
      defaultSecondaryContentColor: ExampleColors.secondary400,
      errorBackgroundColor: ExampleColors.primary900,
      errorContentColor: ExampleColors.secondary800,
      errorSecondaryContentColor: ExampleColors.primary900,
      disabledBackgroundColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledSecondaryContentColor:
          ExampleColors.secondary300.withOpacity(0.7),
    ),
    smallSize: UIKitSizeScheme(
      width: 4,
      height: 6,
      spacing: 4,
      secondarySpacing: 16,
      iconSize: 16,
      labelStyle: ExampleTypography.bodySSemiBold,
      inputStyle: ExampleTypography.body3Regular,
      assistiveStyle: ExampleTypography.bodySRegular,
    ),
    mediumSize: UIKitSizeScheme(
      width: 4,
      height: 12,
      spacing: 6,
      secondarySpacing: 24,
      iconSize: 16,
      labelStyle: ExampleTypography.body3SemiBold,
      inputStyle: ExampleTypography.body2Regular,
      assistiveStyle: ExampleTypography.body3Regular,
    ),
    largeSize: UIKitSizeScheme(
      width: 4,
      height: 6,
      spacing: 8,
      secondarySpacing: 32,
      iconSize: 16,
      labelStyle: ExampleTypography.body2SemiBold,
      inputStyle: ExampleTypography.body1Regular,
      assistiveStyle: ExampleTypography.body2Regular,
    ),
  ),
  toggleSwitchThemeData: UIKitToggleSwitchThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary100,
      defaultBorderColor: ExampleColors.primary800,
      defaultContentColor: ExampleColors.primary700,
      defaultSecondaryContentColor: ExampleColors.secondaryW,
      hoverBackgroundColor: ExampleColors.secondary100,
      hoverBorderColor: ExampleColors.primary900,
      hoverContentColor: ExampleColors.primary800,
      hoverSecondaryContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.secondary100,
      activeBorderColor: ExampleColors.primary900,
      activeContentColor: ExampleColors.primary800,
      activeSecondaryContentColor: ExampleColors.secondaryW,
      focusedBackgroundColor: ExampleColors.secondary100,
      focusedBorderColor: ExampleColors.primary900,
      focusedContentColor: ExampleColors.primary800,
      focusedSecondaryContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary50.withOpacity(0.7),
      disabledBorderColor: Colors.transparent.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledSecondaryContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    shadowScheme: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      hoverShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      activeShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
    ),
    largeSize: UIKitSizeScheme(
      width: 48,
      height: 24,
      borderSize: 1,
      borderRadius: 10,
      spacing: 20,
      iconSize: 16,
    ),
    smallSize: UIKitSizeScheme(
      width: 40,
      height: 20,
      borderSize: 1,
      borderRadius: 8,
      spacing: 16.67,
      iconSize: 13,
    ),
  ),
  checkboxListTileThemeData: UIKitCheckBoxListTileThemeData(
    primaryColors: UIKitColorScheme(
      // background color of the whole widget
      defaultBackgroundColor: ExampleColors.secondaryW,
      // background for the checkbox only
      defaultSecondaryContentColor: ExampleColors.secondary200,
      // border color of the box
      defaultBorderColor: ExampleColors.primary800,
      // color of the checkbox
      defaultContentColor: ExampleColors.primary800,//ExampleColors.primary800,

      hoverBackgroundColor: ExampleColors.primary800,
      hoverBorderColor: ExampleColors.primary800,
      hoverContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.primary800,
      activeBorderColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.primary800,
      focusedBackgroundColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary800,
      focusedContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledBorderColor: ExampleColors.secondary200.withOpacity(0.7),
      disabledContentColor: ExampleColors.secondaryW.withOpacity(0.7),
    ),
    largeSize: UIKitSizeScheme(
      width: 20,
      height: 20,
      iconSize: 20,
      padding: const EdgeInsets.all(2),
      borderSize: 1,
      borderRadius: 6,
      spacing: 12,
    ),
    mediumSize: UIKitSizeScheme(
      width: 20,
      height: 20,
      iconSize: 20,
      padding: const EdgeInsets.all(2),
      borderSize: 1,
      borderRadius: 6,
      spacing: 12,
    ),
    smallSize: UIKitSizeScheme(
      width: 20,
      height: 20,
      iconSize: 20,
      padding: const EdgeInsets.all(2),
      borderSize: 1,
      borderRadius: 6,
      spacing: 12,
    ),
    primaryShadows: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 2,
          spreadRadius: 0,
        ),
      ],
    ),
  ),
  tabThemeData: UIKitTabThemeData(
    pageTabColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary500,
      defaultSecondaryContentColor: ExampleColors.secondary500,
      hoverBackgroundColor: ExampleColors.primary50,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondary500,
      hoverSecondaryContentColor: ExampleColors.secondary500,
      focusedBackgroundColor: ExampleColors.primary800,
      focusedBorderColor: ExampleColors.primary900,
      focusedContentColor: ExampleColors.secondaryW,
      focusedSecondaryContentColor: ExampleColors.secondaryW,
      activeBackgroundColor: ExampleColors.primary700,
      activeBorderColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.secondaryW,
      activeSecondaryContentColor: ExampleColors.secondaryW,
      disabledBackgroundColor: ExampleColors.secondaryW.withOpacity(0.7),
      disabledBorderColor: Colors.transparent,
      disabledContentColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledSecondaryContentColor:
          ExampleColors.secondary300.withOpacity(0.7),
    ),
    pageTabShadowScheme: UIKitShadowScheme(
      activeShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.24),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF58060C).withOpacity(0.16),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
    ),
    pageTabSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
      borderSize: 1,
      borderRadius: 8,
      spacing: 12,
      labelStyle: ExampleTypography.body1SemiBold,
    ),
    lineTabColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW.withOpacity(0.01),
      defaultBorderColor: ExampleColors.secondary400,
      defaultContentColor: ExampleColors.secondary500,
      defaultSecondaryContentColor: ExampleColors.secondary400,
      hoverBackgroundColor: ExampleColors.primary30,
      hoverBorderColor: ExampleColors.secondary400,
      hoverContentColor: ExampleColors.secondary500,
      hoverSecondaryContentColor: ExampleColors.secondary500,
      focusedBackgroundColor: ExampleColors.secondaryW,
      focusedBorderColor: ExampleColors.primary400,
      focusedContentColor: ExampleColors.secondary700,
      focusedSecondaryContentColor: ExampleColors.secondary400,
      activeBackgroundColor: ExampleColors.secondaryW.withOpacity(0.01),
      activeBorderColor: ExampleColors.primary800,
      activeContentColor: ExampleColors.secondary800,
      activeSecondaryContentColor: ExampleColors.primary700,
      disabledBackgroundColor: ExampleColors.secondaryW.withOpacity(0.7),
      disabledBorderColor: Colors.transparent,
      disabledContentColor: ExampleColors.secondary300.withOpacity(0.7),
      disabledSecondaryContentColor:
          ExampleColors.secondary300.withOpacity(0.7),
    ),
    lineTabShadowScheme: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF9F9FAA).withOpacity(0.01),
          offset: const Offset(0, -1),
          blurRadius: 0,
          spreadRadius: 0,
        ),
      ],
      hoverShadow: [
        BoxShadow(
          color: const Color(0xFF9F9FAA).withOpacity(0.01),
          offset: const Offset(0, -1),
          blurRadius: 0,
          spreadRadius: 0,
        ),
      ],
      activeShadow: [
        BoxShadow(
          color: const Color(0xFFE52633).withOpacity(0.01),
          offset: const Offset(0, -2),
          blurRadius: 0,
          spreadRadius: 0,
        ),
      ],
      disabledShadow: [
        BoxShadow(
          color: const Color(0xFFCED5E4).withOpacity(0.01),
          offset: const Offset(0, -1),
          blurRadius: 0,
          spreadRadius: 0,
        ),
      ],
    ),
    lineTabSizeScheme: UIKitSizeScheme(
      height: 40,
      spacing: 4,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.body2Regular,
      padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
    ),
  ),
  textInputThemeData: UIKitTextInputThemeData(
    filledInputColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary50,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondaryK,
      defaultSecondaryContentColor: ExampleColors.secondary600,
      hoverBackgroundColor: ExampleColors.secondary100,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondaryK,
      hoverSecondaryContentColor: ExampleColors.secondary700,
      focusedBackgroundColor: ExampleColors.secondaryW,
      focusedBorderColor: ExampleColors.secondary500,
      focusedContentColor: ExampleColors.secondaryK,
      focusedSecondaryContentColor: ExampleColors.secondary600,
      activeBackgroundColor: ExampleColors.secondary50,
      activeBorderColor: Colors.transparent,
      activeContentColor: ExampleColors.secondaryK,
      activeSecondaryContentColor: ExampleColors.secondary700,
      errorBackgroundColor: ExampleColors.primary30,
      errorBorderColor: Colors.transparent,
      errorContentColor: ExampleColors.secondaryK,
      errorSecondaryContentColor: ExampleColors.primary700,
      disabledBackgroundColor: ExampleColors.secondary30,
      disabledBorderColor: Colors.transparent,
      disabledContentColor: ExampleColors.secondaryK,
      disabledSecondaryContentColor: ExampleColors.secondary300,
    ),
    largeFilledInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      spacing: 8,
      secondarySpacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.body1Regular,
      focusedLabelStyle: ExampleTypography.body3Regular,
      inputStyle: ExampleTypography.body1Regular,
      assistiveStyle: ExampleTypography.body2Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    mediumFilledInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 16),
      spacing: 6,
      secondarySpacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.body2Regular,
      focusedLabelStyle: ExampleTypography.bodySRegular,
      inputStyle: ExampleTypography.body2Regular,
      assistiveStyle: ExampleTypography.body3Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    smallFilledInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 12),
      spacing: 4,
      secondarySpacing: 8,
      borderSize: 1,
      borderRadius: 8,
      labelStyle: ExampleTypography.body3Regular,
      focusedLabelStyle: ExampleTypography.bodyXSRegular,
      inputStyle: ExampleTypography.body3Regular,
      assistiveStyle: ExampleTypography.bodySRegular,
      leadingSize: 16,
      trailingSize: 16,
    ),
    filledInputShadowScheme: UIKitShadowScheme.defaultScheme(),
    lineInputColorScheme: UIKitColorScheme(
      defaultBackgroundColor: Colors.transparent,
      defaultBorderColor: ExampleColors.secondary200,
      defaultContentColor: ExampleColors.secondaryK,
      defaultSecondaryContentColor: ExampleColors.secondary700,
      hoverBackgroundColor: Colors.transparent,
      hoverBorderColor: ExampleColors.secondary300,
      hoverContentColor: ExampleColors.secondaryK,
      hoverSecondaryContentColor: ExampleColors.secondary700,
      focusedBackgroundColor: Colors.transparent,
      focusedBorderColor: ExampleColors.secondary500,
      focusedContentColor: ExampleColors.secondaryK,
      focusedSecondaryContentColor: ExampleColors.secondary800,
      activeBackgroundColor: Colors.transparent,
      activeBorderColor: ExampleColors.secondary200,
      activeContentColor: ExampleColors.secondaryK,
      activeSecondaryContentColor: ExampleColors.secondary700,
      errorBackgroundColor: Colors.transparent,
      errorBorderColor: ExampleColors.primary900,
      errorContentColor: ExampleColors.secondaryK,
      errorSecondaryContentColor: ExampleColors.primary700,
      disabledBackgroundColor: Colors.transparent,
      disabledBorderColor: ExampleColors.secondary300,
      disabledContentColor: ExampleColors.secondaryK,
      disabledSecondaryContentColor: ExampleColors.secondary300,
    ),
    largeLineInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8),
      spacing: 8,
      secondarySpacing: 8,
      borderSize: 1,
      labelStyle: ExampleTypography.body1Regular,
      focusedLabelStyle: ExampleTypography.body3Regular,
      inputStyle: ExampleTypography.body1Regular,
      assistiveStyle: ExampleTypography.body2Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    mediumLineInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 4),
      spacing: 6,
      secondarySpacing: 8,
      borderSize: 1,
      labelStyle: ExampleTypography.body2Regular,
      focusedLabelStyle: ExampleTypography.bodySRegular,
      inputStyle: ExampleTypography.body2Regular,
      assistiveStyle: ExampleTypography.body3Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    smallLineInputSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 4),
      spacing: 4,
      secondarySpacing: 8,
      borderSize: 1,
      labelStyle: ExampleTypography.body3Regular,
      focusedLabelStyle: ExampleTypography.bodyXSRegular,
      inputStyle: ExampleTypography.body3Regular,
      assistiveStyle: ExampleTypography.bodySRegular,
      leadingSize: 16,
      trailingSize: 16,
    ),
    lineInputShadowScheme: UIKitShadowScheme.defaultScheme(),
    filledSearchColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondary30,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary400,
      defaultSecondaryContentColor: Colors.transparent,
      hoverBackgroundColor: ExampleColors.secondary50,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondary500,
      hoverSecondaryContentColor: Colors.transparent,
      focusedBackgroundColor: ExampleColors.secondaryW,
      focusedBorderColor: Colors.transparent,
      focusedContentColor: ExampleColors.secondary900,
      focusedSecondaryContentColor: ExampleColors.secondary500,
      activeBackgroundColor: ExampleColors.secondaryW,
      activeBorderColor: Colors.transparent,
      activeContentColor: ExampleColors.secondary900,
      activeSecondaryContentColor: ExampleColors.secondary700,
      disabledBackgroundColor: ExampleColors.secondaryW,
      disabledBorderColor: Colors.transparent,
      disabledContentColor: ExampleColors.secondary200,
      disabledSecondaryContentColor: Colors.transparent,
    ),
    largeFilledSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 11, horizontal: 16),
      spacing: 8,
      borderRadius: 14,
      borderSize: 1,
      inputStyle: ExampleTypography.body1Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    mediumFilledSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 9, horizontal: 16),
      spacing: 8,
      borderRadius: 12,
      borderSize: 1,
      inputStyle: ExampleTypography.body2Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    smallFilledSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      spacing: 6,
      borderRadius: 10,
      borderSize: 1,
      inputStyle: ExampleTypography.body3Regular,
      leadingSize: 16,
      trailingSize: 16,
    ),
    filledSearchShadowScheme: UIKitShadowScheme(
      focusedShadow: [
        BoxShadow(
          color: const Color(0xFF690A10).withOpacity(0.7),
          blurRadius: 4,
          spreadRadius: 0,
        ),
      ],
    ),
    lineSearchColorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: ExampleColors.secondary200,
      defaultContentColor: ExampleColors.secondaryK,
      defaultSecondaryContentColor: ExampleColors.secondary700,
      hoverBackgroundColor: Colors.transparent,
      hoverBorderColor: ExampleColors.secondary300,
      hoverContentColor: ExampleColors.secondaryK,
      hoverSecondaryContentColor: ExampleColors.secondary700,
      focusedBackgroundColor: Colors.transparent,
      focusedBorderColor: ExampleColors.secondary500,
      focusedContentColor: ExampleColors.secondaryK,
      focusedSecondaryContentColor: ExampleColors.secondary800,
      activeBackgroundColor: Colors.transparent,
      activeBorderColor: ExampleColors.secondary200,
      activeContentColor: ExampleColors.secondaryK,
      activeSecondaryContentColor: ExampleColors.secondary700,
      disabledBackgroundColor: Colors.transparent,
      disabledBorderColor: ExampleColors.secondary300,
      disabledContentColor: ExampleColors.secondaryK,
      disabledSecondaryContentColor: ExampleColors.secondary300,
    ),
    largeLineSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.only(bottom: 8),
      spacing: 8,
      borderSize: 1,
      inputStyle: ExampleTypography.body1Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    mediumLineSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.only(bottom: 8),
      spacing: 8,
      borderSize: 1,
      inputStyle: ExampleTypography.body2Regular,
      leadingSize: 20,
      trailingSize: 16,
    ),
    smallLineSearchSizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.only(bottom: 8),
      spacing: 6,
      borderSize: 1,
      inputStyle: ExampleTypography.body3Regular,
      leadingSize: 16,
      trailingSize: 16,
    ),
    lineSearchShadowScheme: UIKitShadowScheme.defaultScheme(),
  ),
  dropdownMenuThemeData: UIKitDropdownMenuThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
    ),
    sizeScheme: UIKitSizeScheme(
      borderSize: 0,
      borderRadius: 12,
      padding: const EdgeInsets.all(8),
    ),
    shadowScheme: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF301B1D).withOpacity(0.06),
          offset: const Offset(0, 2),
          blurRadius: 3,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF180203).withOpacity(0.1),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
      ],
    ),
  ),
  calendarButtonThemeData: UIKitCalendarButtonThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondaryK,
      defaultSecondaryContentColor: ExampleColors.primary100,
      hoverBackgroundColor: ExampleColors.primary100,
      hoverBorderColor: Colors.transparent,
      hoverContentColor: ExampleColors.secondaryK,
      hoverSecondaryContentColor: ExampleColors.primary100,
      focusedBackgroundColor: ExampleColors.primary800,
      focusedBorderColor: Colors.transparent,
      focusedContentColor: ExampleColors.secondaryK,
      focusedSecondaryContentColor: ExampleColors.primary100,
      activeBackgroundColor: ExampleColors.primary700,
      activeBorderColor: Colors.transparent,
      activeContentColor: ExampleColors.secondaryW,
      activeSecondaryContentColor: ExampleColors.primary100,
      disabledBackgroundColor: ExampleColors.secondaryW,
      disabledBorderColor: Colors.transparent,
      disabledContentColor: ExampleColors.secondary300,
      disabledSecondaryContentColor: ExampleColors.primary100,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
      borderSize: 0,
      borderRadius: 12,
      labelStyle: ExampleTypography.body1SemiBold,
    ),
    shadowScheme: UIKitShadowScheme.defaultScheme(),
  ),
  datePickerThemeData: UIKitDatePickerThemeData(
    colorScheme: UIKitColorScheme(
      defaultBackgroundColor: ExampleColors.secondaryW,
      defaultBorderColor: Colors.transparent,
      defaultContentColor: ExampleColors.secondary800,
    ),
    sizeScheme: UIKitSizeScheme(
      padding: const EdgeInsets.all(24),
      borderSize: 0,
      borderRadius: 8,
      labelStyle: ExampleTypography.body2SemiBold,
    ),
    shadowScheme: UIKitShadowScheme(
      defaultShadow: [
        BoxShadow(
          color: const Color(0xFF0D1556).withOpacity(0.24),
          offset: const Offset(0, 1),
          blurRadius: 2,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF201E8D).withOpacity(0.13),
          offset: const Offset(0, 4),
          blurRadius: 8,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF201E8D).withOpacity(0.07),
          offset: const Offset(0, 8),
          blurRadius: 16,
          spreadRadius: 0,
        ),
        BoxShadow(
          color: const Color(0xFF2B297C).withOpacity(0.08),
          offset: const Offset(0, 16),
          blurRadius: 32,
          spreadRadius: 0,
        ),
      ],
    ),
  ),
);